### ISSUE TITLE
Cartopy 0.15.1 fails to install on travis with no cython

### ISSUE THREAD

**Issue by djhoese** [SciTools/cartopy#1035]
### Description

I added cartopy as an optional dependency to my pyresample package (switching from basemap to cartopy) and the installation failed on travis.

```Collecting cartopy (from pyresample==1.8.1)
  Downloading Cartopy-0.15.1.tar.gz (8.2MB)
    100% |████████████████████████████████| 8.2MB 168kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-hkgucrv5/cartopy/setup.py", line 45, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hkgucrv5/cartopy/setup.py", line 47, in <module>
        raise ImportError('Cython 0.15.1+ is required to install cartopy.')
    ImportError: Cython 0.15.1+ is required to install cartopy.
```

Here's the entire job if you want it: https://travis-ci.org/pytroll/pyresample/jobs/344927488

I see this was addressed in #725 but doesn't seem to be working anymore.

I guess my main concern here is why is Cython needed by the user at installation time? Can't you either store the C/C++ files in the repository and therefore the source tarball or just include them in the built tarball. That way the Cython dependency shouldn't be needed.

<details>
 <summary>Full environment definition</summary>

### Operating system

Travis CI Image - Linux/Ubuntu

### Cartopy version

0.15.1

### conda list

See travis build above.

### pip list

See travis build above.

</details>

**Comment by dopplershift** [comment]
Most projects are going away from having them in the git repo. I'm not sure what it takes to include them in the tarball.

What we should probably do is have wheels uploaded to pypi; which would first require @pelson to actually upload the latest tarball (0.16) to pypi. (hint hint) 😁 

In all seriousness, @pelson would you merge a PR that uploaded at least the tarball (from Travis) to PyPI when you cut a new tag? How do you feel about wheels?

**Comment by davidh-ssec** [comment]
> Most projects are going away from having them in the git repo

I've seen this expressed by other projects too. One of the other VisPy maintainers suggested it too. In PyResample we've been putting them in the repository, but that's because I implemented that. I think the only thing needed is to include the C/C++ in the MANIFEST.in and when you run `python setup.py sdist` I *think* they get built and included. It puts responsibility on the packager, but removes the cython dependence for the user.

**Comment by dopplershift** [comment]
Personally, I'd be ok with them in the tarball; they just have no business being under version control.

**Comment by pelson** [comment]
I'm OK with having the cython generated source in the sdist (again, ideally not in the repo though).
We would need to update the setup to make it conditionally import cython.

I've just pushed the v0.16.0 sdist to pypi (without any of the cython generated files).

wrt to cython being in the setup_requires but still having this issue, I found the docs illuminating:

> (Note: projects listed in setup_requires will NOT be automatically installed on the system where the setup script is being run. They are simply downloaded to the ./.eggs directory if they’re not locally available already. If you want them to be installed, as well as being available when the setup script is run, you should add them to install_requires and setup_requires.)

In short, I think we should definitely try to improve the situation, but am not entirely comfortable going the whole way down to providing pre-built binary wheels. 


CC @QuLogic as somebody who was involved in setting up setup_requires in setup.py. What is your take?

**Comment by QuLogic** [comment]
I thought there was some kind of consensus to not cythonize files for sdist when I wrote that, but I can't really find any discussion. The files can be added to the sdist, but I'm also -1 on adding to the repo.

I also don't think we should provide pre-build binary wheels unless we can do something about #805.

**Comment by dopplershift** [comment]
Yeah, I agree about probably needing to address ABI compatibility with Shapely before shipping binary wheels--at least now forcing people to build makes it more likely things work (though certainly not guaranteed).

@pelson How would you feel about me adding to Travis a deploy step to automatically upload the sdist to PyPI when you tag a release? I have that working seamlessly on MetPy.

**Comment by dopplershift** [comment]
With the release of pip 10, we may be able to solve this by adding a `pyproject.toml`.

**Comment by pelson** [comment]
> @pelson How would you feel about me adding to Travis a deploy step to automatically upload the sdist to PyPI when you tag a release? I have that working seamlessly on MetPy.

👍 sounds great.

**Comment by maxim-lian** [comment]
We just hit this, as part of having `cartopy` in a `requirements.txt` and `pip -r` installing. Because `pip` doesn't install in a dependable order, `cartopy` can fail even if `Cython` is also in the `requirements.txt`

One option would be to specify `Cython` as an `install_requires` in `setup.py` - then pip is able to do build the dependency graph and install cython first

**Comment by noahhsmith** [comment]
Showstopper for us - not at all clear on the topics involved but it's the one package out of several that's not playing nice. Fingers crossed it magically goes away:)

**Comment by pelson** [comment]
I believe this should be solved by #1132 for v0.17 of cartopy. Please re-open if this isn't resolved for that release.

Thanks,
